apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sba-site
  template:
    metadata:
      labels:
        app: sba-site
    spec:
      containers:
      - name: sba-site
        image: abdallauno1/sbaimage
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sba-service
spec:
  selector:
    app: sba-site
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
